---
development: &defaults
  adapter:  sqlite3
  database: db/development.db

test:
  adapter:  sqlite3
  database: ':memory:'

production:
  adapter:  sqlite3
  database: db/production.db

rake:
  <<: *defaults
